language: node_js
node_js:
  - "7"
cache:
  yarn: true
before_install:
  - npm install -g yarn
install:
  - yarn install
script:
  - yarn run lint
deploy:
  provider: script
  script: yarn install && yarn run publish
  on:
    branch: master